name: RosePvP
version: '${project.version}'
main: com.keisa1333.rosepvp.RosePvP
api-version: '1.19'
author: GuR
depend: [ Vault ]

commands:
  rosepvp:
    description: rose command
    aliases: [ rose ]
  ffa:
    description: rose command
  tdm:
    description: rose command
  sd:
    description: rose command
  dom:
    description: rose command
  cq:
    description: rose command
  inf:
    description: rose command
  leave:
    description: rose command
  menu:
    description: rose command
    aliases: [ mn ]

permissions:
  rose.admin:
    default: op
    description: Gives full access to the plugin